### ISSUE TITLE
Cases where Blackjack credits does not get added to the account

### ISSUE THREAD

**Issue by DavidYJC** [Drew61854/TerminalGames#1] opened 2024-01-07 19:01 UTC
Hello, just testing out the mod and found that sometimes in the Blackjack game credits does not get added to the account when the game ends. I am using quite a bit of mods so not sure if that have any affects. 

![20240107105044_1](https://github.com/Drew61854/TerminalGames/assets/87910468/1f9a599b-e88b-4a8f-9901-6eb922eaf6ba)
![20240107104744_1](https://github.com/Drew61854/TerminalGames/assets/87910468/95e06cd8-15cd-4e94-81a6-d7c30aa5233e)

**Comment by Drew61854** [comment] 2024-01-08 01:46
@DavidYJC 
Hello, and thanks for the issue. If possible could you include the mod list you are using? Looking over the code I don't see why this would be happening, and I wasn't able to replicate it in my testing, so I do think there's some sort of mod incompatibility that I might be able to fix.

**Comment by DavidYJC** [comment] 2024-01-08 06:39
@Drew61854 Thanks for the reply, the mod list is a bit long but regardless, I will put it in here at the end. As far as I could tell the only mod that might affect this could be "alexsio-gamba_mod-1.0.8"? When I have TerminalGames activated, that mod would simply not work. Maybe the "bet" command shared by both mods causes this?

I also took a look at the code and maybe found what is causing the issue? My coding is a bit rusty so forgive me if I am wrong on this.



In this part of TerminalGames.BlackjackMethods.StandBlackJack

else if (num3 == num2)
			{
				num = 3;
				text2 = text2 + "That's " + num3 + ", tie! Your bet of " + ConsoleGamesMain.currentBet + " was returned to your account.\n\n";
			}
			else if (num3 < num2)
			{
				num = 1;
				text2 = text2 + "That's " + num3 + ", so the dealer must stand. You win " + ConsoleGamesMain.currentBet + " credits.\n\n";



I noticed that in cases "else if (num3 == num2)" and "else if (num3 < num2)" Banker.MoneyManip were not called and that might be what's causing the issue. 



**Mod List**
BepInEx-BepInExPack-5.4.2100
Sligili-HDLethalCompany-1.5.6
PopleZoo-BetterItemScan-3.0.0
alexsio-gamba_mod-1.0.8
JunLethalCompany-GamblingMachineAtTheCompany-1.1.2
Sligili-More_Emotes-1.2.2
Verity-3rdPerson-1.1.0
FlipMods-ReservedItemSlotCore-1.7.7
FlipMods-ReservedFlashlightSlot-1.5.7
FlipMods-ReservedWalkieSlot-1.5.3
FlipMods-ObjectVolumeController-1.0.3
KoderTeh-Boombox_Controller-1.1.5
FutureSavior-Boombox_Sync_Fix-1.1.2
FlipMods-TooManyEmotes-1.7.6
notnotnotswipez-MoreCompany-1.7.2
x753-More_Suits-1.4.1
Hexnet111-SuitSaver-1.1.2
jombi-SuitsAndCosmetics-1.0.8
Verity-TooManySuits-1.0.5
GorillaBeast-GorillaSuits-0.0.10
OnePeak-Low_Budget_One_Piece_suits-0.5.1
Crabford-Clown_Suit-1.0.0
ViViKo-AmongUsSuits-1.0.2
ManiaBania-1000_Quota_Stare-1.0.0
Dwarggo-Fashion_Company-1.3.0
MythicFrog-FrogSkins-1.0.11
GhostbustingTrio-CustomFunSuits-1.8.2
KingTyphon-AnimeSkins-1.0.5
e_sex_club-E_SEX_GOONER_SUITS_3000-1.0.3
qwq_cloud-Boykisser_uwu_Suit-1.1.2
ViViKo-MemeSuits-1.1.0
Akky-DripSuits-1.0.0
AliCat-Drip_Suit-1.0.1
ExioMadeThis-Ahegao_Suit-1.0.0
Team_Waluigi-WaluigiSuit-0.0.3
Vezcom-clownass_suit-1.0.0
hyper4venom-Minecraft_Steve_Suit-1.0.0
A_Really_Big_Dog-Yakuza_Suits-1.1.0
GigaChads-MemeSuitSkins-1.0.2
BrotherPig-MountainDewMan_Suits-1.0.2
Hexa-Hexas_Cosmetics-0.0.2
EliteMasterEric-WackyCosmetics-1.1.0
ZTK-ZTKCosmetics-2.0.0
bandaidroo-BandaidsMegaCosmetics-1.0.0
rooni-JiggleUtils-0.1.0
rooni-MoreTails-1.2.1
Evaisa-HookGenPatcher-0.0.5
Evaisa-LethalLib-0.10.1
Flof-MemeSoundboard-1.1.2
femboytv-LethalPosters-1.2.0
femboytv-LethalPaintings-1.2.0
McDucky-LethalPaintingsSync-0.0.2
PanHouse-LethalClunk-1.1.1
ViViKo-MoreMaterials-1.3.1
akechii-DiscountAlert-2.3.0
KodiCraft-TermSpeak-1.1.0
TheFluff-FairAI-1.2.7
299792458-MoreMoneyStart-2.1.0
RickArg-Helmet_Cameras-2.1.5
RATS_RND_division-firearmlicense-1.1.0
Tyzeron-Minimap-1.0.5
Mom_Llama-Lethal_Company_Enhancer-0.1.10
GameMasterDevs-GameMaster-3.2.0
Jordo-NeedyCats-1.1.1
Evaisa-LethalThings-0.8.8
stormytuna-RouteRandom-1.2.2
Stoneman-LethalProgression-1.3.2
willis81808-HackPad-1.1.3
willis81808-LethalSettings-1.3.0
Electric131-OuijaBoard-1.5.1
dancemoon-DanceTools-1.1.1
RugbugRedfern-Skinwalkers-2.0.3
anormaltwig-LateCompany-1.0.10
Backrooms-Backrooms-0.1.3
ENZ-Lock_Doors_Mod-1.1.0
darksnakex-DanceHealingOnShip-2.2.0
HolographicWings-LethalExpansion-1.3.16
ake-Dust2-1.2.0
silhygames-FumoCompany-1.2.0
rainbow137-MinecraftScraps-1.3.0
Pinta-PintoBoy-1.0.3
Taker-CannabisCompany-1.0.0
CHILLAX-ChillaxSCRAPS-0.5.2
goblinfiend-Druggie-1.2.0
NotAtomicBomb-TerminalApi-1.5.0
SoulWithMae-CompanyExecutive-3.0.0
malco-Lategame_Upgrades-2.8.6
Midge-PushCompany-1.2.0
Monkeytype-HideChat-1.0.0
FutureSavior-Hold_Scan_Button-1.1.1
Bobbie-LethalRebinding-1.0.0
ButteryStancakes-KeepUnlocks-1.0.1
SZAKI-RemoteRemastered-1.0.2
Sant5050-Buy_Any_Ship_Decoration-1.0.0
egeadam-MoreScreams-1.0.3
TwinDimensionalProductions-CoilHeadStare-1.0.3
no00ob-LCSoundTool-1.4.0
Clementinise-CustomSounds-2.2.0
Deli-Chipi_Chipi_Dropship-2.0.1
rafl-BonkHitSfxFixed-1.0.2
TheFluff-GetLootForKills-1.1.8
Oni_Hazza-ToyRobot_MaxwellTheme-1.1.3
MetalPipeSFX-HornMoan-2.1.0
flillip-ActualClownHorn-1.0.1
AnnoyingApple24-SevenNationLoudHorn-1.0.2
itsmeowdev-DoorFix-1.0.0
Blorb-WeatherMultipliers-1.1.0
FlipMods-LetMeLookDown-1.0.1
Rattenbonkers-TVLoader-1.1.1
Drakorle-MoreItems-1.0.1
Nephren-MrCrabsQuota-1.1.0
NutNutty-AlwaysPickup-1.2.0
Hamunii-JetpackWarning-2.2.0
Piggy-ShowCapacity-1.0.7
EliteMasterEric-Coroner-1.5.3
Jamil-Corporate_Restructure-1.0.5
taffyko-NameplateTweaks-1.0.6
HoffmanTV-angry_british_bug-1.4.1
Kirkwood-Spore_Lizard_KSI_scream-1.0.0
Arffeh-WhyAreYouRunning-0.9.1
EliteMasterEric-CleanerLogs-1.0.0
XDev-SimpleCommandAPI-1.0.1
Garbage_Mammal-TerminalGames-1.2.0

**Comment by Drew61854** [comment] 2024-01-08 18:31
@DavidYJC 
Oof, that's a little embarrassing not going to lie. I had the 'else' part of StandBlackJack collapsed so I didn't see any of it...you're right that is what the problem is, I forgot to update the money when the dealer has to draw. I don't know how I failed to get the bug to replicate the other day, I must have gotten a lot of 17+ initial draws. Oh well, it's been fixed now. I'll include it in the next update, I appreciate you reporting this.
Also yes, the gamba mod and my mod don't work together because they both use the 'bet' command, so whichever mod is loaded first will be overridden by the second, in your case my mod overrides the gamba mod. I might try and get around that somehow also, but for now it's just how it is.

**Closed as completed by Drew61854** 2024-01-08 18:31 UTC
Labels: bug

**Comment by DavidYJC** [comment] 2024-01-08 18:42
@Drew61854 Alright thank you so much for the updates and hope you have a great day!
